version: "3.8"

services:
  web:
    # image: radioactive1109/r3-scraper:v1
    container_name: web-container
    build:
      context: .
      dockerfile: Dockerfile
      args:
        requirements_file: requirements.txt
    ports:
      - "80:8000"
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:latest
    container_name: db-container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
    driver: local
